-- 在 Supabase Dashboard 的 SQL Editor 中执行；本脚本可安全重复执行。
create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  username text not null check (char_length(username) between 1 and 32),
  comment text not null check (char_length(comment) between 1 and 300),
  star smallint not null check (star between 1 and 5),
  tags jsonb not null default '[]'::jsonb,
  source boolean not null default true,
  likes integer not null default 0 check (likes >= 0),
  created_at timestamptz not null default now()
);

-- 为旧版本表补充点赞字段。
alter table public.reviews
  add column if not exists likes integer not null default 0 check (likes >= 0);

alter table public.reviews enable row level security;

drop policy if exists "Anyone can read reviews" on public.reviews;
drop policy if exists "Anyone can submit a review" on public.reviews;

create policy "Anyone can read reviews"
on public.reviews for select to anon using (true);

create policy "Anyone can submit a review"
on public.reviews for insert to anon with check (
  char_length(username) between 1 and 32
  and char_length(comment) between 1 and 300
  and star between 1 and 5
);

-- 原子递增点赞数，前端无法直接篡改其他字段。
create or replace function public.increment_review_likes(review_id bigint)
returns void
language sql
security definer
set search_path = public
as $$
  update public.reviews set likes = likes + 1 where id = review_id;
$$;

grant execute on function public.increment_review_likes(bigint) to anon;
