-- 在 Supabase Dashboard 的 SQL Editor 中执行此文件。
create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  username text not null check (char_length(username) between 1 and 32),
  comment text not null check (char_length(comment) between 1 and 300),
  star smallint not null check (star between 1 and 5),
  tags jsonb not null default '[]'::jsonb,
  source boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.reviews enable row level security;

create policy "Anyone can read reviews"
on public.reviews for select to anon using (true);

create policy "Anyone can submit a review"
on public.reviews for insert to anon with check (
  char_length(username) between 1 and 32
  and char_length(comment) between 1 and 300
  and star between 1 and 5
);
